version: "3.9"

services:
  backend:
    build: ./backend
    image: backend_image
    ports:
      - "8000:8000"
    # Add any additional configuration for your backend service here.
    # For example, environment variables, volumes, etc.

  neo4j:
    build: ./neo4j
    image: gradvek_neo4j_image
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
