version: "3.9"

services:
  neo4j:
    build: ./neo4j
    image: gradvek_neo4j
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins

