version: "3.9"

networks:
  my_network:
    driver: bridge

services:
  neo4j:
    build: ./neo4j
    image: gradvek_neo4j
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - "7474:7474"
      - "7687:7687"
    # volumes section is only for initial loading of data
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    networks:
      - my_network

  backend:
    build: ./backend
    image: gradvek_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - my_network
    # Add any additional configuration for your backend service here.
    # For example, environment variables, volumes, etc.
