name: Gradvek CI/CD

on:
  workflow_dispatch:
    inputs:
      NON_MAIN_DEPLOY:
        description: 'Deploy from workflow dispatch'
        required: false
        default: 'true'
  push:
    branches:
      - '**'

jobs:
  dependencies:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          service: ["backend", "frontend"]
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Cache backend dependencies
          if: matrix.service == 'backend'
          uses: actions/cache@v3
          with:
            path: backend/env
            key: backend-deps-${{ hashFiles('backend/requirements.txt') }}
            restore-keys: |
              backend-deps-

        - name: Cache frontend dependencies
          if: matrix.service == 'frontend'
          uses: actions/cache@v3
          with:
            path: frontend/node_modules
            key: frontend-deps-${{ hashFiles('frontend/package-lock.json') }}
            restore-keys: |
              frontend-deps-

        - name: Install backend dependencies
          if: matrix.service == 'backend'
          run: |
            cd backend
            python -m venv env
            source env/bin/activate
            pip install -r requirements.txt

        - name: Install frontend dependencies
          if: matrix.service == 'frontend'
          run: |
            cd frontend
            npm ci

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    environment: ns_dockerhub
    strategy:
      matrix:
        service: ["backend", "frontend"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore backend dependencies
        if: matrix.service == 'backend'
        uses: actions/cache@v3
        with:
          path: backend/env
          key: backend-deps-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            backend-deps-

      - name: Restore frontend dependencies
        if: matrix.service == 'frontend'
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: frontend-deps-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            frontend-deps-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.service }}
          restore-keys: |
            ${{ runner.os }}-$-${{ matrix.service }}
            ${{ runner.os }}-

      - name: Build Docker images
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gradvek-${{ matrix.service }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  publish:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') ||  github.event.inputs.NON_MAIN_DEPLOY == 'TRUE'
    needs: build
    runs-on: ubuntu-latest
    environment: ns_dockerhub
    strategy:
      matrix:
        service: ["backend", "frontend"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gradvek-${{ matrix.service }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache


  # deploy:
  #   if: (github.event_name == 'pull_request' && github.ref == 'refs/heads/main') ||  github.event.inputs.NON_MAIN_DEPLOY == 'TRUE'
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   environment: ns_dockerhub
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{


